#! /bin/sh
echo "dnsserver"

rm /var/log/nginx/*

sudo service nginx restart

echo "nginx " #  >> dnsserver.log

sudo service unbound restart

echo "unbound" # >> dnsserver.log


sudo service AdGuardHome restart

echo "adguard" # >> dnsserver.log
 
echo "finished @" $(date) # >> dnsserver.log
